import snapshotJson from "./snapshot.json";

/**
 * Typed access to src/data/sources/snapshot.json, generated by
 * scripts/data/build_snapshot.py from BLS 4.0 and USDA FoodData Central.
 */

export const SOURCE_DBS = ["BLS", "FDC"] as const;
export type SourceDb = (typeof SOURCE_DBS)[number];

export const PROVENANCE_CATEGORIES = [
  "analysis",
  "literature",
  "aggregation",
  "database",
  "recipe",
  "pattern",
  "borrowed",
  "rescaled",
  "formula",
  "logicalZero",
  "assumption",
  "trace",
  "label",
] as const;
export type ProvenanceCategory = (typeof PROVENANCE_CATEGORIES)[number];

export const NUTRIENT_KEYS = [
  "kcal",
  "water",
  "protein",
  "fat",
  "carbsAvailable",
  "fibre",
  "sugars",
  "starch",
  "lactose",
  "his",
  "ile",
  "leu",
  "lys",
  "met",
  "cys",
  "phe",
  "tyr",
  "thr",
  "trp",
  "val",
  "sfa",
  "mufa",
  "pufa",
  "ala",
  "epa",
  "dpa",
  "dha",
  "la",
  "aa",
  "c15",
  "c17",
  "cla",
  "retinol",
  "betaCarotene",
  "vitaminARae",
  "vitaminD",
  "vitaminE",
  "vitaminK",
  "thiamin",
  "riboflavin",
  "niacin",
  "vitaminB6",
  "folate",
  "vitaminB12",
  "vitaminC",
  "choline",
  "sodium",
  "potassium",
  "calcium",
  "magnesium",
  "phosphorus",
  "iron",
  "zinc",
  "copper",
  "iodine",
  "selenium",
  "cholesterol",
  "provitaminAOther",
] as const;
export type NutrientKey = (typeof NUTRIENT_KEYS)[number];

export interface NutrientProvenance {
  category: ProvenanceCategory;
  db: SourceDb;
}

export interface SourceEntry {
  db: SourceDb;
  code: string;
  name: { de?: string; en: string };
  /** Only on the secondary entry: whether it is the same food and preparation or a stand-in. */
  match?: "same" | "similar";
}

export interface DatasetMeta {
  title: string;
  publisher: string;
  year: number;
  license: string;
  url: string;
  citation: string;
  archiveSha256: string;
  doi?: string;
  release?: string;
}

type SnapshotValue = [number, ProvenanceCategory, SourceDb] | null;

interface SnapshotFood {
  sources: SourceEntry[];
  values: Record<NutrientKey, SnapshotValue>;
  aminoAcidPattern?: string;
}

interface Snapshot {
  generatedBy: string;
  datasets: Record<SourceDb, DatasetMeta>;
  units: Record<NutrientKey, string>;
  foods: Record<string, SnapshotFood>;
}

export const SNAPSHOT = snapshotJson as unknown as Snapshot;
export const DATASETS = SNAPSHOT.datasets;
export const NUTRIENT_UNITS = SNAPSHOT.units;

export interface SourcedFood {
  sources: SourceEntry[];
  aminoAcidPattern?: string;
  /** Value per 100 g edible portion, or null when no source reports it. */
  value(key: NutrientKey): number | null;
  provenance(key: NutrientKey): NutrientProvenance | null;
}

export function sourcedFood(id: string): SourcedFood {
  const entry = SNAPSHOT.foods[id];
  if (!entry) {
    throw new Error(`No snapshot entry for food "${id}"; add it to manifest.json and rebuild`);
  }
  return {
    sources: entry.sources,
    aminoAcidPattern: entry.aminoAcidPattern,
    value: (key) => entry.values[key]?.[0] ?? null,
    provenance: (key) => {
      const hit = entry.values[key];
      return hit ? { category: hit[1], db: hit[2] } : null;
    },
  };
}
