import type {
  AnimalExclusiveMarkers,
  Food,
  FattyAcidsGPer100g,
  MicrosPer100g,
  ResidueProfile,
} from "../types/domain.ts";

const NONE_ANIMAL: AnimalExclusiveMarkers = {
  creatine: false,
  taurine: false,
  carnosine: false,
  longChainEpaDha: false,
  activeB12: false,
  hemeIron: false,
  preformedRetinol: false,
};

const MUSCLE_ANIMAL: AnimalExclusiveMarkers = {
  creatine: true,
  taurine: true,
  carnosine: true,
  longChainEpaDha: false,
  activeB12: true,
  hemeIron: true,
  preformedRetinol: true,
};

function starchFrom(total: number, sugars: number, fiber: number): number {
  return Math.max(0, total - sugars - fiber);
}

function linoleicFrom(pufa: number, ala: number, epa: number, dha: number): number {
  return Math.max(0, pufa - ala - epa - dha);
}

function plantResidue(partial: Omit<ResidueProfile, "sourceId">): ResidueProfile {
  return { ...partial, sourceId: "usda-pdp" };
}

function fa(input: {
  sfa: number;
  mufa: number;
  pufa: number;
  ala: number;
  epa?: number;
  dha?: number;
  cla?: number;
  oddChain?: number;
  claFlag?: FattyAcidsGPer100g["claFlag"];
  oddChainFlag?: FattyAcidsGPer100g["oddChainFlag"];
}): FattyAcidsGPer100g {
  const epa = input.epa ?? 0;
  const dha = input.dha ?? 0;
  return {
    sfa: input.sfa,
    mufa: input.mufa,
    pufa: input.pufa,
    ala: input.ala,
    epa,
    dha,
    linoleic: linoleicFrom(input.pufa, input.ala, epa, dha),
    cla: input.cla ?? 0,
    oddChain: input.oddChain ?? 0,
    claFlag: input.claFlag ?? "estimate",
    oddChainFlag: input.oddChainFlag ?? "estimate",
  };
}

function plantMicros(
  input: {
    ironMg: number;
    zincMg: number;
    vitaminARaeUg: number;
    vitaminCMg: number;
    b12Ug: number;
    folateUg: number;
    cholineMg: number;
    vitaminDUg: number;
    phytateBound?: boolean;
    b12Form?: MicrosPer100g["b12Form"];
    vitaminAForm?: MicrosPer100g["vitaminAForm"];
    carotenoidFraction?: number;
    iodineUg?: number;
    iodineFlag?: MicrosPer100g["iodineFlag"];
  },
): MicrosPer100g {
  return {
    ironMg: input.ironMg,
    ironForm: "nonheme",
    hemeFraction: 0,
    zincMg: input.zincMg,
    zincBoundToPhytate: input.phytateBound ?? true,
    vitaminARaeUg: input.vitaminARaeUg,
    vitaminAForm: input.vitaminAForm ?? "carotenoid",
    carotenoidFraction: input.carotenoidFraction ?? 1,
    vitaminCMg: input.vitaminCMg,
    b12Ug: input.b12Ug,
    b12Form: input.b12Form ?? "absent",
    folateUg: input.folateUg,
    cholineMg: input.cholineMg,
    vitaminDUg: input.vitaminDUg,
    iodineUg: input.iodineUg ?? 0,
    iodineFlag: input.iodineFlag ?? "estimate",
  };
}

export const FOODS: readonly Food[] = [
  {
    id: "spinach-raw",
    name: "Spinach, raw",
    nameDe: "Spinat, roh",
    kingdom: "plant",
    foodClass: "leafy_salad",
    fdcId: 168462,
    state: "raw",
    energyKcal: 23,
    proteinG: 2.86,
    fatG: 0.39,
    aminoAcids: {
      his: 0.064,
      ile: 0.147,
      leu: 0.223,
      lys: 0.174,
      met: 0.053,
      cys: 0.035,
      phe: 0.129,
      tyr: 0.108,
      thr: 0.122,
      trp: 0.039,
      val: 0.161,
    },
    fattyAcids: fa({ sfa: 0.063, mufa: 0.01, pufa: 0.165, ala: 0.138 }),
    carbs: {
      total: 3.63,
      sugars: 0.42,
      fiber: 2.2,
      starch: starchFrom(3.63, 0.42, 2.2),
      starchFlag: "derived",
      resistantStarch: 0.1,
      resistantStarchFlag: "estimate",
    },
    micros: plantMicros({
      ironMg: 2.71,
      zincMg: 0.53,
      vitaminARaeUg: 469,
      vitaminCMg: 28.1,
      b12Ug: 0,
      folateUg: 194,
      cholineMg: 19.3,
      vitaminDUg: 0,
    }),
    quality: {
      ilealDigestibility: 0.72,
      digestibilityFlag: "literature",
      digestibilitySourceId: "who-fao-2013",
      publishedDiaas: null,
      publishedPdcaas: null,
      qualityIndexSourceId: null,
      phytateMg: 80,
      phytateFlag: "estimate",
      phytochemicalTags: ["carotenoids", "nitrate", "polyphenols"],
      residue: plantResidue({
        pdpDetectRate: 0.72,
        heavyMetalRisk: 0.25,
        mercuryRisk: 0,
        iodineExcessRisk: 0,
        note: "Leafy greens have high USDA PDP detect rates; cadmium can accumulate in spinach.",
      }),
      waterActivity: 0.96,
      fermented: false,
      dried: false,
    },
    animalExclusive: NONE_ANIMAL,
    sourceIds: ["usda-fdc-sr", "usda-pdp", "hurrell-egli-2010", "iom-vitamina"],
    notes: [
      "Vitamin A is carotenoid-derived (FDC RAE already uses 12:1 β-carotene). Completeness remains incomplete.",
      "Non-heme iron 2.71 mg/100 g is not equivalent to heme iron of the same mass.",
    ],
  },
  {
    id: "romaine-raw",
    name: "Romaine lettuce, raw",
    nameDe: "Romanasalat, roh",
    kingdom: "plant",
    foodClass: "leafy_salad",
    fdcId: 169247,
    state: "raw",
    energyKcal: 17,
    proteinG: 1.23,
    fatG: 0.3,
    aminoAcids: {
      his: 0.021,
      ile: 0.045,
      leu: 0.076,
      lys: 0.064,
      met: 0.015,
      cys: 0.006,
      phe: 0.065,
      tyr: 0.025,
      thr: 0.043,
      trp: 0.01,
      val: 0.055,
    },
    fattyAcids: fa({ sfa: 0.039, mufa: 0.012, pufa: 0.16, ala: 0.113 }),
    carbs: {
      total: 3.29,
      sugars: 1.19,
      fiber: 2.1,
      starch: starchFrom(3.29, 1.19, 2.1),
      starchFlag: "derived",
      resistantStarch: 0.05,
      resistantStarchFlag: "estimate",
    },
    micros: plantMicros({
      ironMg: 0.97,
      zincMg: 0.23,
      vitaminARaeUg: 436,
      vitaminCMg: 4,
      b12Ug: 0,
      folateUg: 136,
      cholineMg: 9.9,
      vitaminDUg: 0,
    }),
    quality: {
      ilealDigestibility: 0.7,
      digestibilityFlag: "literature",
      digestibilitySourceId: "who-fao-2013",
      publishedDiaas: null,
      publishedPdcaas: null,
      qualityIndexSourceId: null,
      phytateMg: 30,
      phytateFlag: "estimate",
      phytochemicalTags: ["carotenoids", "nitrate"],
      residue: plantResidue({
        pdpDetectRate: 0.58,
        heavyMetalRisk: 0.12,
        mercuryRisk: 0,
        iodineExcessRisk: 0,
        note: "Lettuce is a frequent PDP residue commodity; typically lower than spinach.",
      }),
      waterActivity: 0.97,
      fermented: false,
      dried: false,
    },
    animalExclusive: NONE_ANIMAL,
    sourceIds: ["usda-fdc-sr", "usda-pdp", "iom-vitamina"],
    notes: ["Salad-class leafy green. Protein density is too low to treat as a protein food."],
  },
  {
    id: "kale-boiled",
    name: "Kale, boiled",
    nameDe: "Grünkohl, gekocht",
    kingdom: "plant",
    foodClass: "leafy_salad",
    fdcId: 169238,
    state: "boiled, drained, unsalted",
    energyKcal: 36,
    proteinG: 2.94,
    fatG: 1.21,
    aminoAcids: {
      his: 0.172,
      ile: 0.176,
      leu: 0.205,
      lys: 0.176,
      met: 0.029,
      cys: 0.039,
      phe: 0.15,
      tyr: 0.104,
      thr: 0.131,
      trp: 0.035,
      val: 0.16,
    },
    fattyAcids: fa({ sfa: 0.175, mufa: 0.102, pufa: 0.66, ala: 0.371 }),
    carbs: {
      total: 5.3,
      sugars: 1.21,
      fiber: 4,
      starch: starchFrom(5.3, 1.21, 4),
      starchFlag: "derived",
      resistantStarch: 0.2,
      resistantStarchFlag: "estimate",
    },
    micros: plantMicros({
      ironMg: 0.84,
      zincMg: 0.27,
      vitaminARaeUg: 146,
      vitaminCMg: 17.8,
      b12Ug: 0,
      folateUg: 65,
      cholineMg: 0.4,
      vitaminDUg: 0,
    }),
    quality: {
      ilealDigestibility: 0.74,
      digestibilityFlag: "literature",
      digestibilitySourceId: "who-fao-2013",
      publishedDiaas: null,
      publishedPdcaas: null,
      qualityIndexSourceId: null,
      phytateMg: 60,
      phytateFlag: "estimate",
      phytochemicalTags: ["carotenoids", "glucosinolates"],
      residue: plantResidue({
        pdpDetectRate: 0.68,
        heavyMetalRisk: 0.18,
        mercuryRisk: 0,
        iodineExcessRisk: 0,
        note: "Kale is both leafy (residue surface) and brassica (glucosinolates). Classed as leafy/salad.",
      }),
      waterActivity: 0.93,
      fermented: false,
      dried: false,
    },
    animalExclusive: NONE_ANIMAL,
    sourceIds: ["usda-fdc-sr", "usda-pdp"],
    notes: ["Boiling lowers vitamin C versus raw kale; FDC values are for the boiled state."],
  },
  {
    id: "lentils-boiled",
    name: "Lentils, boiled",
    nameDe: "Linsen, gekocht",
    kingdom: "plant",
    foodClass: "legumes_beans",
    fdcId: 172421,
    state: "mature seeds, boiled, unsalted",
    energyKcal: 116,
    proteinG: 9.02,
    fatG: 0.38,
    aminoAcids: {
      his: 0.254,
      ile: 0.39,
      leu: 0.654,
      lys: 0.63,
      met: 0.077,
      cys: 0.118,
      phe: 0.445,
      tyr: 0.241,
      thr: 0.323,
      trp: 0.081,
      val: 0.448,
    },
    fattyAcids: fa({ sfa: 0.053, mufa: 0.064, pufa: 0.175, ala: 0.037 }),
    carbs: {
      total: 20.13,
      sugars: 1.8,
      fiber: 7.9,
      starch: starchFrom(20.13, 1.8, 7.9),
      starchFlag: "derived",
      resistantStarch: 3.4,
      resistantStarchFlag: "estimate",
    },
    micros: plantMicros({
      ironMg: 3.33,
      zincMg: 1.27,
      vitaminARaeUg: 0,
      vitaminCMg: 1.5,
      b12Ug: 0,
      folateUg: 181,
      cholineMg: 32.7,
      vitaminDUg: 0,
      phytateBound: true,
    }),
    quality: {
      ilealDigestibility: 0.8,
      digestibilityFlag: "literature",
      digestibilitySourceId: "who-fao-2013",
      publishedDiaas: 0.75,
      publishedPdcaas: 0.63,
      qualityIndexSourceId: "phillips-2017-diaas",
      phytateMg: 280,
      phytateFlag: "estimate",
      phytochemicalTags: ["polyphenols"],
      residue: plantResidue({
        pdpDetectRate: 0.22,
        heavyMetalRisk: 0.1,
        mercuryRisk: 0,
        iodineExcessRisk: 0,
        note: "Dry pulses are lower-residue commodities than leafy greens after cooking/dilution.",
      }),
      waterActivity: 0.75,
      fermented: false,
      dried: false,
    },
    animalExclusive: NONE_ANIMAL,
    sourceIds: ["usda-fdc-sr", "who-fao-2013", "rs-legumes", "hurrell-egli-2010"],
    notes: [
      "Sulfur amino acids are typically limiting. Published DIAAS ~0.75 is used when present; still incomplete.",
      "Resistant starch 3.4 g/100 g is a cooked-pulse literature estimate, not an FDC field.",
    ],
  },
  {
    id: "black-beans-boiled",
    name: "Black beans, boiled",
    nameDe: "Schwarze Bohnen, gekocht",
    kingdom: "plant",
    foodClass: "legumes_beans",
    fdcId: 175237,
    state: "mature seeds, boiled, with salt",
    energyKcal: 132,
    proteinG: 8.86,
    fatG: 0.54,
    aminoAcids: {
      his: 0.247,
      ile: 0.391,
      leu: 0.708,
      lys: 0.608,
      met: 0.133,
      cys: 0.096,
      phe: 0.479,
      tyr: 0.25,
      thr: 0.373,
      trp: 0.105,
      val: 0.464,
    },
    fattyAcids: fa({ sfa: 0.139, mufa: 0.047, pufa: 0.231, ala: 0.105 }),
    carbs: {
      total: 23.71,
      sugars: 0.32,
      fiber: 8.7,
      starch: starchFrom(23.71, 0.32, 8.7),
      starchFlag: "derived",
      resistantStarch: 2.8,
      resistantStarchFlag: "estimate",
    },
    micros: plantMicros({
      ironMg: 2.1,
      zincMg: 1.12,
      vitaminARaeUg: 0,
      vitaminCMg: 0,
      b12Ug: 0,
      folateUg: 149,
      cholineMg: 32.6,
      vitaminDUg: 0,
    }),
    quality: {
      ilealDigestibility: 0.76,
      digestibilityFlag: "literature",
      digestibilitySourceId: "who-fao-2013",
      publishedDiaas: null,
      publishedPdcaas: 0.75,
      qualityIndexSourceId: "phillips-2017-diaas",
      phytateMg: 300,
      phytateFlag: "estimate",
      phytochemicalTags: ["polyphenols"],
      residue: plantResidue({
        pdpDetectRate: 0.2,
        heavyMetalRisk: 0.1,
        mercuryRisk: 0,
        iodineExcessRisk: 0,
        note: "FDC record is 'with salt' (237 mg Na). Scoring does not treat sodium as a residue.",
      }),
      waterActivity: 0.76,
      fermented: false,
      dried: false,
    },
    animalExclusive: NONE_ANIMAL,
    sourceIds: ["usda-fdc-sr", "rs-legumes"],
    notes: ["High fibre and resistant starch; sulfur amino acids remain the usual limit."],
  },
  {
    id: "tofu-calcium",
    name: "Tofu, regular, calcium-set",
    nameDe: "Tofu, calcium-gesetzt",
    kingdom: "plant",
    foodClass: "legumes_beans",
    fdcId: 172476,
    state: "raw, regular, calcium sulfate",
    energyKcal: 76,
    proteinG: 8.08,
    fatG: 4.78,
    aminoAcids: {
      his: 0.221,
      ile: 0.435,
      leu: 0.713,
      lys: 0.452,
      met: 0.108,
      cys: 0.029,
      phe: 0.428,
      tyr: 0.359,
      thr: 0.402,
      trp: 0.12,
      val: 0.446,
    },
    fattyAcids: fa({ sfa: 0.691, mufa: 1.056, pufa: 2.699, ala: 0.319 }),
    carbs: {
      total: 1.87,
      sugars: 0.62,
      fiber: 0.3,
      starch: starchFrom(1.87, 0.62, 0.3),
      starchFlag: "derived",
      resistantStarch: 0.1,
      resistantStarchFlag: "estimate",
    },
    micros: plantMicros({
      ironMg: 5.36,
      zincMg: 0.8,
      vitaminARaeUg: 0,
      vitaminCMg: 0.1,
      b12Ug: 0,
      folateUg: 15,
      cholineMg: 28.8,
      vitaminDUg: 0,
      phytateBound: true,
    }),
    quality: {
      ilealDigestibility: 0.86,
      digestibilityFlag: "literature",
      digestibilitySourceId: "who-fao-2013",
      publishedDiaas: 0.91,
      publishedPdcaas: 0.91,
      qualityIndexSourceId: "phillips-2017-diaas",
      phytateMg: 150,
      phytateFlag: "estimate",
      phytochemicalTags: ["isoflavones"],
      residue: plantResidue({
        pdpDetectRate: 0.18,
        heavyMetalRisk: 0.12,
        mercuryRisk: 0,
        iodineExcessRisk: 0,
        note: "Soy isolate DIAAS can approach 0.90–1.0; this food is still labelled incomplete (plant kingdom).",
      }),
      waterActivity: 0.9,
      fermented: false,
      dried: false,
    },
    animalExclusive: NONE_ANIMAL,
    sourceIds: ["usda-fdc-sr", "phillips-2017-diaas", "burdge-2006"],
    notes: [
      "Highest plant protein quality in this sample. Not labelled complete. No EPA/DHA; ALA only.",
      "Calcium-set tofu iron is non-heme.",
    ],
  },
  {
    id: "mung-sprouts",
    name: "Mung bean sprouts, raw",
    nameDe: "Mungobohnensprossen, roh",
    kingdom: "plant",
    foodClass: "sprouts",
    fdcId: 169256,
    state: "sprouted, raw — SR Legacy NDB 11043 values",
    energyKcal: 30,
    proteinG: 3.04,
    fatG: 0.18,
    aminoAcids: {
      his: 0.07,
      ile: 0.132,
      leu: 0.175,
      lys: 0.166,
      met: 0.034,
      cys: 0.017,
      phe: 0.117,
      tyr: 0.052,
      thr: 0.078,
      trp: 0.037,
      val: 0.13,
    },
    fattyAcids: fa({ sfa: 0.046, mufa: 0.022, pufa: 0.058, ala: 0.018 }),
    carbs: {
      total: 5.94,
      sugars: 4.13,
      fiber: 1.8,
      starch: starchFrom(5.94, 4.13, 1.8),
      starchFlag: "derived",
      resistantStarch: 0.2,
      resistantStarchFlag: "estimate",
    },
    micros: plantMicros({
      ironMg: 0.91,
      zincMg: 0.41,
      vitaminARaeUg: 1,
      vitaminCMg: 13.2,
      b12Ug: 0,
      folateUg: 61,
      cholineMg: 14.4,
      vitaminDUg: 0,
      phytateBound: false,
    }),
    quality: {
      ilealDigestibility: 0.78,
      digestibilityFlag: "literature",
      digestibilitySourceId: "who-fao-2013",
      publishedDiaas: null,
      publishedPdcaas: null,
      qualityIndexSourceId: null,
      phytateMg: 20,
      phytateFlag: "estimate",
      phytochemicalTags: ["polyphenols"],
      residue: plantResidue({
        pdpDetectRate: 0.12,
        heavyMetalRisk: 0.08,
        mercuryRisk: 0,
        iodineExcessRisk: 0,
        note: "Sprouts are a distinct class: lower pesticide than field leaf, higher perishability/microbial handling risk (not an MRL term).",
      }),
      waterActivity: 0.98,
      fermented: false,
      dried: false,
    },
    animalExclusive: NONE_ANIMAL,
    sourceIds: ["usda-fdc-sr"],
    notes: [
      "FDC 169256 in some dumps maps to mustard greens; nutrient amounts here follow SR Legacy mung sprouts (NDB 11043).",
      "Sprouting lowers phytate versus the dry bean but does not complete the protein.",
    ],
  },
  {
    id: "broccoli-raab",
    name: "Broccoli raab, raw",
    nameDe: "Cime di rapa, roh",
    kingdom: "plant",
    foodClass: "cruciferous_kraut",
    fdcId: 170381,
    state: "raw",
    energyKcal: 22,
    proteinG: 3.17,
    fatG: 0.49,
    aminoAcids: {
      his: 0.066,
      ile: 0.104,
      leu: 0.17,
      lys: 0.198,
      met: 0.048,
      cys: 0.039,
      phe: 0.128,
      tyr: 0.075,
      thr: 0.106,
      trp: 0.043,
      val: 0.153,
    },
    fattyAcids: fa({ sfa: 0.083, mufa: 0.044, pufa: 0.218, ala: 0.189 }),
    carbs: {
      total: 2.85,
      sugars: 0.38,
      fiber: 2.7,
      starch: starchFrom(2.85, 0.38, 2.7),
      starchFlag: "derived",
      resistantStarch: 0.1,
      resistantStarchFlag: "estimate",
    },
    micros: plantMicros({
      ironMg: 2.14,
      zincMg: 0.77,
      vitaminARaeUg: 131,
      vitaminCMg: 20.2,
      b12Ug: 0,
      folateUg: 83,
      cholineMg: 18.3,
      vitaminDUg: 0,
    }),
    quality: {
      ilealDigestibility: 0.74,
      digestibilityFlag: "literature",
      digestibilitySourceId: "who-fao-2013",
      publishedDiaas: null,
      publishedPdcaas: null,
      qualityIndexSourceId: null,
      phytateMg: 40,
      phytateFlag: "estimate",
      phytochemicalTags: ["glucosinolates", "carotenoids"],
      residue: plantResidue({
        pdpDetectRate: 0.48,
        heavyMetalRisk: 0.12,
        mercuryRisk: 0,
        iodineExcessRisk: 0,
        note: "Fresh crucifer — not fermented. Distinct from sauerkraut in the same class.",
      }),
      waterActivity: 0.95,
      fermented: false,
      dried: false,
    },
    animalExclusive: NONE_ANIMAL,
    sourceIds: ["usda-fdc-sr", "usda-pdp"],
    notes: ["Glucosinolate-bearing brassica. Classed as cruciferous/kraut, not leafy/salad."],
  },
  {
    id: "sauerkraut",
    name: "Sauerkraut, canned",
    nameDe: "Sauerkraut, Dose",
    kingdom: "plant",
    foodClass: "cruciferous_kraut",
    fdcId: 169279,
    state: "canned, solids and liquids",
    energyKcal: 19,
    proteinG: 0.91,
    fatG: 0.14,
    aminoAcids: {
      his: 0.016,
      ile: 0.021,
      leu: 0.029,
      lys: 0.029,
      met: 0.009,
      cys: 0.008,
      phe: 0.023,
      tyr: 0.014,
      thr: 0.021,
      trp: 0.008,
      val: 0.024,
    },
    fattyAcids: fa({ sfa: 0.03, mufa: 0.013, pufa: 0.047, ala: 0.02 }),
    carbs: {
      total: 4.28,
      sugars: 1.78,
      fiber: 2.9,
      starch: starchFrom(4.28, 1.78, 2.9),
      starchFlag: "derived",
      resistantStarch: 0.15,
      resistantStarchFlag: "estimate",
    },
    micros: plantMicros({
      ironMg: 1.47,
      zincMg: 0.19,
      vitaminARaeUg: 1,
      vitaminCMg: 14.7,
      b12Ug: 0,
      folateUg: 24,
      cholineMg: 10.4,
      vitaminDUg: 0,
      phytateBound: false,
    }),
    quality: {
      ilealDigestibility: 0.72,
      digestibilityFlag: "literature",
      digestibilitySourceId: "who-fao-2013",
      publishedDiaas: null,
      publishedPdcaas: null,
      qualityIndexSourceId: null,
      phytateMg: 10,
      phytateFlag: "estimate",
      phytochemicalTags: ["glucosinolates", "fermented_acids"],
      residue: plantResidue({
        pdpDetectRate: 0.28,
        heavyMetalRisk: 0.08,
        mercuryRisk: 0,
        iodineExcessRisk: 0,
        note: "Fermentation and brine washing typically reduce surface residues versus raw cabbage. Sodium is high and is not a residue term.",
      }),
      waterActivity: 0.94,
      fermented: true,
      dried: false,
    },
    animalExclusive: NONE_ANIMAL,
    sourceIds: ["usda-fdc-sr"],
    notes: [
      "Fermented crucifer — not collapsed with fresh broccoli raab or with fermented dairy.",
      "Amino-acid grams are scaled from cabbage-class SR profiles (protein 0.91 g) and flagged by low protein density.",
    ],
  },
  {
    id: "white-mushroom",
    name: "White mushrooms, raw",
    nameDe: "Champignons, roh",
    kingdom: "plant",
    foodClass: "mushrooms",
    fdcId: 169251,
    state: "raw",
    energyKcal: 22,
    proteinG: 3.09,
    fatG: 0.34,
    aminoAcids: {
      his: 0.057,
      ile: 0.076,
      leu: 0.12,
      lys: 0.107,
      met: 0.031,
      cys: 0.012,
      phe: 0.085,
      tyr: 0.044,
      thr: 0.107,
      trp: 0.035,
      val: 0.232,
    },
    fattyAcids: fa({ sfa: 0.05, mufa: 0, pufa: 0.16, ala: 0 }),
    carbs: {
      total: 3.26,
      sugars: 1.98,
      fiber: 1,
      starch: starchFrom(3.26, 1.98, 1),
      starchFlag: "derived",
      resistantStarch: 0,
      resistantStarchFlag: "measured",
    },
    micros: plantMicros({
      ironMg: 0.5,
      zincMg: 0.52,
      vitaminARaeUg: 0,
      vitaminCMg: 2.1,
      b12Ug: 0.04,
      b12Form: "analog",
      folateUg: 17,
      cholineMg: 17.3,
      vitaminDUg: 0.2,
      vitaminAForm: "carotenoid",
      phytateBound: false,
    }),
    quality: {
      ilealDigestibility: 0.7,
      digestibilityFlag: "literature",
      digestibilitySourceId: "who-fao-2013",
      publishedDiaas: null,
      publishedPdcaas: null,
      qualityIndexSourceId: null,
      phytateMg: 0,
      phytateFlag: "estimate",
      phytochemicalTags: ["ergothioneine", "beta_glucan"],
      residue: plantResidue({
        pdpDetectRate: 0.3,
        heavyMetalRisk: 0.35,
        mercuryRisk: 0,
        iodineExcessRisk: 0,
        note: "Fungi bioaccumulate some metals. Not a plant leaf and not an alga.",
      }),
      waterActivity: 0.95,
      fermented: false,
      dried: false,
    },
    animalExclusive: NONE_ANIMAL,
    sourceIds: ["usda-fdc-sr", "who-b12"],
    notes: [
      "FDC lists 0.04 µg B12; scored as analog / not assumed bioactive.",
      "Chitin/beta-glucan fibre is not the same as leafy cellulose; class stays mushrooms.",
    ],
  },
  {
    id: "nori-laver",
    name: "Nori (laver), raw",
    nameDe: "Nori (Laver), roh",
    kingdom: "plant",
    foodClass: "algae_seaweed",
    fdcId: 168458,
    state: "raw",
    energyKcal: 35,
    proteinG: 5.81,
    fatG: 0.28,
    aminoAcids: {
      his: 0.14,
      ile: 0.259,
      leu: 0.501,
      lys: 0.222,
      met: 0.145,
      cys: 0.1,
      phe: 0.273,
      tyr: 0.254,
      thr: 0.232,
      trp: 0.043,
      val: 0.402,
    },
    fattyAcids: fa({ sfa: 0.061, mufa: 0.025, pufa: 0.11, ala: 0.001, epa: 0.08, dha: 0 }),
    carbs: {
      total: 5.11,
      sugars: 0.49,
      fiber: 0.3,
      starch: starchFrom(5.11, 0.49, 0.3),
      starchFlag: "derived",
      resistantStarch: 0,
      resistantStarchFlag: "estimate",
    },
    micros: plantMicros({
      ironMg: 1.8,
      zincMg: 1.05,
      vitaminARaeUg: 260,
      vitaminCMg: 39,
      b12Ug: 0,
      b12Form: "analog",
      folateUg: 146,
      cholineMg: 10.4,
      vitaminDUg: 0,
      iodineUg: 1470,
      iodineFlag: "estimate",
      phytateBound: false,
    }),
    quality: {
      ilealDigestibility: 0.72,
      digestibilityFlag: "literature",
      digestibilitySourceId: "who-fao-2013",
      publishedDiaas: null,
      publishedPdcaas: null,
      qualityIndexSourceId: null,
      phytateMg: 0,
      phytateFlag: "estimate",
      phytochemicalTags: ["algae_pigments", "carotenoids"],
      residue: plantResidue({
        pdpDetectRate: 0.1,
        heavyMetalRisk: 0.4,
        mercuryRisk: 0.08,
        iodineExcessRisk: 0.55,
        note: "Seaweed iodine and metal accumulation are the residue story, not farm pesticides.",
      }),
      waterActivity: 0.9,
      fermented: false,
      dried: false,
    },
    animalExclusive: {
      ...NONE_ANIMAL,
      longChainEpaDha: true,
    },
    sourceIds: ["usda-fdc-sr", "iodine-seaweed", "who-b12", "burdge-2006"],
    notes: [
      "Contains EPA (0.08 g/100 g) — a rare plant-kingdom long-chain n-3. Still not a complete protein.",
      "FDC B12 is 0; nori B12 reports elsewhere are treated as analogs unless confirmed active.",
      "Iodine 1470 µg/100 g is a literature-range estimate for raw laver, not an FDC field.",
    ],
  },
  {
    id: "wakame",
    name: "Wakame, raw",
    nameDe: "Wakame, roh",
    kingdom: "plant",
    foodClass: "algae_seaweed",
    fdcId: 170496,
    state: "raw",
    energyKcal: 45,
    proteinG: 3.03,
    fatG: 0.64,
    aminoAcids: {
      his: 0.015,
      ile: 0.087,
      leu: 0.257,
      lys: 0.112,
      met: 0.063,
      cys: 0.028,
      phe: 0.112,
      tyr: 0.049,
      thr: 0.165,
      trp: 0.035,
      val: 0.209,
    },
    fattyAcids: fa({ sfa: 0.13, mufa: 0.058, pufa: 0.218, ala: 0.002, epa: 0.186, dha: 0 }),
    carbs: {
      total: 9.14,
      sugars: 0.65,
      fiber: 0.5,
      starch: starchFrom(9.14, 0.65, 0.5),
      starchFlag: "derived",
      resistantStarch: 0,
      resistantStarchFlag: "estimate",
    },
    micros: plantMicros({
      ironMg: 2.18,
      zincMg: 0.38,
      vitaminARaeUg: 18,
      vitaminCMg: 3,
      b12Ug: 0,
      b12Form: "analog",
      folateUg: 196,
      cholineMg: 13.9,
      vitaminDUg: 0,
      iodineUg: 4200,
      iodineFlag: "estimate",
      phytateBound: false,
    }),
    quality: {
      ilealDigestibility: 0.7,
      digestibilityFlag: "literature",
      digestibilitySourceId: "who-fao-2013",
      publishedDiaas: null,
      publishedPdcaas: null,
      qualityIndexSourceId: null,
      phytateMg: 0,
      phytateFlag: "estimate",
      phytochemicalTags: ["algae_pigments"],
      residue: plantResidue({
        pdpDetectRate: 0.1,
        heavyMetalRisk: 0.42,
        mercuryRisk: 0.08,
        iodineExcessRisk: 0.8,
        note: "Wakame iodine can exceed daily needs in a small serving. Excess is a residue-axis term.",
      }),
      waterActivity: 0.9,
      fermented: false,
      dried: false,
    },
    animalExclusive: {
      ...NONE_ANIMAL,
      longChainEpaDha: true,
    },
    sourceIds: ["usda-fdc-sr", "iodine-seaweed", "who-b12"],
    notes: ["Higher EPA than nori in this FDC record. Histidine is limiting. Distinct from mushrooms and leafy salads."],
  },
  {
    id: "sweet-potato-raw",
    name: "Sweet potato, raw",
    nameDe: "Süßkartoffel, roh",
    kingdom: "plant",
    foodClass: "roots_tubers",
    fdcId: 168482,
    state: "raw, unprepared",
    energyKcal: 86,
    proteinG: 1.57,
    fatG: 0.05,
    aminoAcids: {
      his: 0.031,
      ile: 0.055,
      leu: 0.092,
      lys: 0.066,
      met: 0.029,
      cys: 0.022,
      phe: 0.089,
      tyr: 0.034,
      thr: 0.083,
      trp: 0.031,
      val: 0.086,
    },
    fattyAcids: fa({ sfa: 0.018, mufa: 0.001, pufa: 0.014, ala: 0.001 }),
    carbs: {
      total: 20.12,
      sugars: 4.18,
      fiber: 3,
      starch: starchFrom(20.12, 4.18, 3),
      starchFlag: "derived",
      resistantStarch: 1.1,
      resistantStarchFlag: "estimate",
    },
    micros: plantMicros({
      ironMg: 0.61,
      zincMg: 0.3,
      vitaminARaeUg: 709,
      vitaminCMg: 2.4,
      b12Ug: 0,
      folateUg: 11,
      cholineMg: 12.3,
      vitaminDUg: 0,
      phytateBound: false,
    }),
    quality: {
      ilealDigestibility: 0.74,
      digestibilityFlag: "literature",
      digestibilitySourceId: "who-fao-2013",
      publishedDiaas: null,
      publishedPdcaas: null,
      qualityIndexSourceId: null,
      phytateMg: 20,
      phytateFlag: "estimate",
      phytochemicalTags: ["carotenoids"],
      residue: plantResidue({
        pdpDetectRate: 0.14,
        heavyMetalRisk: 0.08,
        mercuryRisk: 0,
        iodineExcessRisk: 0,
        note: "Roots typically show lower PDP detect rates than leafy commodities.",
      }),
      waterActivity: 0.86,
      fermented: false,
      dried: false,
    },
    animalExclusive: NONE_ANIMAL,
    sourceIds: ["usda-fdc-sr", "usda-pdp", "iom-vitamina", "rs-legumes"],
    notes: ["Carotenoid vitamin A is high in RAE; bioavailability caution still applies. Active starch is scored separately from fibre."],
  },
  {
    id: "tomato-raw",
    name: "Tomato, raw",
    nameDe: "Tomate, roh",
    kingdom: "plant",
    foodClass: "other_vegetables",
    fdcId: 170457,
    state: "red, ripe, year-round average",
    energyKcal: 18,
    proteinG: 0.88,
    fatG: 0.2,
    aminoAcids: {
      his: 0.014,
      ile: 0.018,
      leu: 0.025,
      lys: 0.027,
      met: 0.006,
      cys: 0.009,
      phe: 0.027,
      tyr: 0.014,
      thr: 0.027,
      trp: 0.006,
      val: 0.018,
    },
    fattyAcids: fa({ sfa: 0.028, mufa: 0.031, pufa: 0.083, ala: 0.003 }),
    carbs: {
      total: 3.89,
      sugars: 2.63,
      fiber: 1.2,
      starch: starchFrom(3.89, 2.63, 1.2),
      starchFlag: "derived",
      resistantStarch: 0,
      resistantStarchFlag: "estimate",
    },
    micros: plantMicros({
      ironMg: 0.27,
      zincMg: 0.17,
      vitaminARaeUg: 42,
      vitaminCMg: 13.7,
      b12Ug: 0,
      folateUg: 15,
      cholineMg: 6.7,
      vitaminDUg: 0,
      phytateBound: false,
    }),
    quality: {
      ilealDigestibility: 0.7,
      digestibilityFlag: "literature",
      digestibilitySourceId: "who-fao-2013",
      publishedDiaas: null,
      publishedPdcaas: null,
      qualityIndexSourceId: null,
      phytateMg: 5,
      phytateFlag: "estimate",
      phytochemicalTags: ["carotenoids", "polyphenols"],
      residue: plantResidue({
        pdpDetectRate: 0.36,
        heavyMetalRisk: 0.08,
        mercuryRisk: 0,
        iodineExcessRisk: 0,
        note: "Fruiting vegetable — medium PDP band, distinct from leafy and from roots.",
      }),
      waterActivity: 0.96,
      fermented: false,
      dried: false,
    },
    animalExclusive: NONE_ANIMAL,
    sourceIds: ["usda-fdc-sr", "usda-pdp"],
    notes: ["Lycopene/carotenoids are the phytochemical story. Not a protein food."],
  },
  {
    id: "beef-85-broiled",
    name: "Beef, ground 85%, broiled",
    nameDe: "Rinderhack 85 %, gegrillt",
    kingdom: "animal",
    foodClass: "muscle_ruminant",
    fdcId: 174032,
    state: "85% lean / 15% fat, patty, broiled",
    energyKcal: 250,
    proteinG: 25.93,
    fatG: 15.41,
    aminoAcids: {
      his: 0.604,
      ile: 0.822,
      leu: 1.45,
      lys: 1.54,
      met: 0.478,
      cys: 0.191,
      phe: 0.725,
      tyr: 0.572,
      thr: 0.72,
      trp: 0.094,
      val: 0.914,
    },
    fattyAcids: fa({
      sfa: 5.895,
      mufa: 6.668,
      pufa: 0.484,
      ala: 0.044,
      epa: 0.003,
      dha: 0.001,
      cla: 0.055,
      oddChain: 0.12,
      claFlag: "estimate",
      oddChainFlag: "estimate",
    }),
    carbs: {
      total: 0,
      sugars: 0,
      fiber: 0,
      starch: 0,
      starchFlag: "measured",
      resistantStarch: 0,
      resistantStarchFlag: "measured",
    },
    micros: {
      ironMg: 2.6,
      ironForm: "heme",
      hemeFraction: 0.65,
      zincMg: 6.31,
      zincBoundToPhytate: false,
      vitaminARaeUg: 3,
      vitaminAForm: "retinol",
      carotenoidFraction: 0,
      vitaminCMg: 0,
      b12Ug: 2.64,
      b12Form: "active",
      folateUg: 9,
      cholineMg: 82.4,
      vitaminDUg: 0,
      iodineUg: 0,
      iodineFlag: "estimate",
    },
    quality: {
      ilealDigestibility: 0.94,
      digestibilityFlag: "literature",
      digestibilitySourceId: "who-fao-2013",
      publishedDiaas: 1.16,
      publishedPdcaas: 0.92,
      qualityIndexSourceId: "phillips-2017-diaas",
      phytateMg: 0,
      phytateFlag: "measured",
      phytochemicalTags: [],
      residue: {
        pdpDetectRate: 0.08,
        heavyMetalRisk: 0.12,
        mercuryRisk: 0,
        iodineExcessRisk: 0,
        note: "Muscle meat: veterinary residues possible; pesticide PDP is not the main term.",
        sourceId: "efsa-mrl",
      },
      waterActivity: 0.75,
      fermented: false,
      dried: false,
    },
    animalExclusive: MUSCLE_ANIMAL,
    sourceIds: ["usda-fdc-sr", "phillips-2017-diaas", "who-fao-2013", "cla-ruminant"],
    notes: [
      "Published DIAAS 1.16. Complete protein under the animal + pattern + digestibility rule.",
      "CLA 0.055 g and odd-chain 0.12 g/100 g are ruminant-fat literature estimates, not FDC fields.",
    ],
  },
  {
    id: "pork-loin-raw",
    name: "Pork loin, raw (enhanced)",
    nameDe: "Schweinefilet, roh",
    kingdom: "animal",
    foodClass: "muscle_monogastric",
    fdcId: 168320,
    state: "boneless loin, fresh — branded SR record",
    energyKcal: 145,
    proteinG: 19.02,
    fatG: 7.18,
    aminoAcids: {
      his: 0.78,
      ile: 0.92,
      leu: 1.58,
      lys: 1.76,
      met: 0.52,
      cys: 0.23,
      phe: 0.79,
      tyr: 0.68,
      thr: 0.85,
      trp: 0.23,
      val: 1.01,
    },
    fattyAcids: fa({ sfa: 2.84, mufa: 3.42, pufa: 0.64, ala: 0.05 }),
    carbs: {
      total: 0.76,
      sugars: 0.08,
      fiber: 0,
      starch: 0.68,
      starchFlag: "derived",
      resistantStarch: 0,
      resistantStarchFlag: "measured",
    },
    micros: {
      ironMg: 0.6,
      ironForm: "heme",
      hemeFraction: 0.55,
      zincMg: 1.6,
      zincBoundToPhytate: false,
      vitaminARaeUg: 2,
      vitaminAForm: "retinol",
      carotenoidFraction: 0,
      vitaminCMg: 1.3,
      b12Ug: 0.5,
      b12Form: "active",
      folateUg: 0,
      cholineMg: 70,
      vitaminDUg: 0.5,
      iodineUg: 0,
      iodineFlag: "estimate",
    },
    quality: {
      ilealDigestibility: 0.93,
      digestibilityFlag: "literature",
      digestibilitySourceId: "who-fao-2013",
      publishedDiaas: 1.17,
      publishedPdcaas: 0.97,
      qualityIndexSourceId: "phillips-2017-diaas",
      phytateMg: 0,
      phytateFlag: "measured",
      phytochemicalTags: [],
      residue: {
        pdpDetectRate: 0.1,
        heavyMetalRisk: 0.1,
        mercuryRisk: 0,
        iodineExcessRisk: 0,
        note: "Branded 'always tender' loin is sodium-enhanced (358 mg). Monogastric — no CLA/odd-chain bonus.",
        sourceId: "efsa-mrl",
      },
      waterActivity: 0.78,
      fermented: false,
      dried: false,
    },
    animalExclusive: MUSCLE_ANIMAL,
    sourceIds: ["usda-fdc-sr", "phillips-2017-diaas"],
    notes: [
      "Amino-acid grams for this branded record were incomplete in FDC; EAA profile is a pork-loin SR literature fill and is noted as such.",
      "Choline and B12 for this SKU were not complete in the pulled subset — choline 70 mg is a pork-loin literature typical, flagged by the note.",
    ],
  },
  {
    id: "chicken-meat-raw",
    name: "Chicken meat, raw",
    nameDe: "Hähnchenfleisch, roh",
    kingdom: "animal",
    foodClass: "muscle_poultry",
    fdcId: 171052,
    state: "broilers, meat only, raw",
    energyKcal: 119,
    proteinG: 21.39,
    fatG: 3.08,
    aminoAcids: {
      his: 0.664,
      ile: 1.13,
      leu: 1.605,
      lys: 1.818,
      met: 0.592,
      cys: 0.274,
      phe: 0.849,
      tyr: 0.722,
      thr: 0.904,
      trp: 0.25,
      val: 1.061,
    },
    fattyAcids: fa({ sfa: 0.79, mufa: 0.9, pufa: 0.75, ala: 0.02, epa: 0.01, dha: 0.03 }),
    carbs: {
      total: 0,
      sugars: 0,
      fiber: 0,
      starch: 0,
      starchFlag: "measured",
      resistantStarch: 0,
      resistantStarchFlag: "measured",
    },
    micros: {
      ironMg: 0.89,
      ironForm: "heme",
      hemeFraction: 0.45,
      zincMg: 1.54,
      zincBoundToPhytate: false,
      vitaminARaeUg: 16,
      vitaminAForm: "retinol",
      carotenoidFraction: 0,
      vitaminCMg: 2.3,
      b12Ug: 0.37,
      b12Form: "active",
      folateUg: 7,
      cholineMg: 65.7,
      vitaminDUg: 0.1,
      iodineUg: 0,
      iodineFlag: "estimate",
    },
    quality: {
      ilealDigestibility: 0.92,
      digestibilityFlag: "literature",
      digestibilitySourceId: "who-fao-2013",
      publishedDiaas: 1.08,
      publishedPdcaas: 0.95,
      qualityIndexSourceId: "phillips-2017-diaas",
      phytateMg: 0,
      phytateFlag: "measured",
      phytochemicalTags: [],
      residue: {
        pdpDetectRate: 0.1,
        heavyMetalRisk: 0.08,
        mercuryRisk: 0,
        iodineExcessRisk: 0,
        note: "Poultry muscle: complete protein, less heme iron and creatine than ruminant.",
        sourceId: "efsa-mrl",
      },
      waterActivity: 0.78,
      fermented: false,
      dried: false,
    },
    animalExclusive: MUSCLE_ANIMAL,
    sourceIds: ["usda-fdc-sr", "phillips-2017-diaas"],
    notes: ["Complete EAA profile. Lower iron than beef. Trace EPA/DHA only."],
  },
  {
    id: "salmon-atlantic-raw",
    name: "Atlantic salmon, farmed, raw",
    nameDe: "Atlantischer Lachs, farm, roh",
    kingdom: "animal",
    foodClass: "muscle_fish",
    fdcId: 175167,
    state: "farmed, raw",
    energyKcal: 208,
    proteinG: 20.42,
    fatG: 13.42,
    aminoAcids: {
      his: 0.549,
      ile: 0.968,
      leu: 1.615,
      lys: 1.87,
      met: 0.626,
      cys: 0.219,
      phe: 0.845,
      tyr: 0.759,
      thr: 0.86,
      trp: 0.209,
      val: 1.107,
    },
    fattyAcids: fa({
      sfa: 3.05,
      mufa: 3.77,
      pufa: 3.886,
      ala: 0.148,
      epa: 0.862,
      dha: 1.104,
    }),
    carbs: {
      total: 0,
      sugars: 0,
      fiber: 0,
      starch: 0,
      starchFlag: "measured",
      resistantStarch: 0,
      resistantStarchFlag: "measured",
    },
    micros: {
      ironMg: 0.34,
      ironForm: "heme",
      hemeFraction: 0.4,
      zincMg: 0.36,
      zincBoundToPhytate: false,
      vitaminARaeUg: 58,
      vitaminAForm: "retinol",
      carotenoidFraction: 0,
      vitaminCMg: 3.9,
      b12Ug: 3.23,
      b12Form: "active",
      folateUg: 26,
      cholineMg: 78.5,
      vitaminDUg: 11,
      iodineUg: 14,
      iodineFlag: "estimate",
    },
    quality: {
      ilealDigestibility: 0.93,
      digestibilityFlag: "literature",
      digestibilitySourceId: "who-fao-2013",
      publishedDiaas: 1.09,
      publishedPdcaas: 1,
      qualityIndexSourceId: "phillips-2017-diaas",
      phytateMg: 0,
      phytateFlag: "measured",
      phytochemicalTags: [],
      residue: {
        pdpDetectRate: 0.05,
        heavyMetalRisk: 0.15,
        mercuryRisk: 0.18,
        iodineExcessRisk: 0.02,
        note: "FDA/EPA lower-mercury group versus swordfish/shark. Farmed fish also have feed-contaminant context.",
        sourceId: "fda-mercury-fish",
      },
      waterActivity: 0.8,
      fermented: false,
      dried: false,
    },
    animalExclusive: {
      ...MUSCLE_ANIMAL,
      longChainEpaDha: true,
    },
    sourceIds: ["usda-fdc-sr", "fda-mercury-fish", "who-fao-2013"],
    notes: ["EPA+DHA 1.966 g/100 g. PUFA oxidation raises the degradation vulnerability term."],
  },
  {
    id: "beef-liver-braised",
    name: "Beef liver, braised",
    nameDe: "Rinderleber, geschmort",
    kingdom: "animal",
    foodClass: "organs",
    fdcId: 168626,
    state: "braised",
    energyKcal: 191,
    proteinG: 29.08,
    fatG: 5.26,
    aminoAcids: {
      his: 0.879,
      ile: 1.352,
      leu: 2.67,
      lys: 2.247,
      met: 0.759,
      cys: 0.526,
      phe: 1.515,
      tyr: 1.128,
      thr: 1.215,
      trp: 0.368,
      val: 1.761,
    },
    fattyAcids: fa({ sfa: 2.947, mufa: 1.124, pufa: 1.109, ala: 0.017 }),
    carbs: {
      total: 5.13,
      sugars: 0,
      fiber: 0,
      starch: 5.13,
      starchFlag: "derived",
      resistantStarch: 0,
      resistantStarchFlag: "measured",
    },
    micros: {
      ironMg: 6.54,
      ironForm: "heme",
      hemeFraction: 0.7,
      zincMg: 5.3,
      zincBoundToPhytate: false,
      vitaminARaeUg: 9442,
      vitaminAForm: "retinol",
      carotenoidFraction: 0.02,
      vitaminCMg: 1.9,
      b12Ug: 70.58,
      b12Form: "active",
      folateUg: 253,
      cholineMg: 426,
      vitaminDUg: 1.2,
      iodineUg: 0,
      iodineFlag: "estimate",
    },
    quality: {
      ilealDigestibility: 0.92,
      digestibilityFlag: "literature",
      digestibilitySourceId: "who-fao-2013",
      publishedDiaas: 1.1,
      publishedPdcaas: 1,
      qualityIndexSourceId: "phillips-2017-diaas",
      phytateMg: 0,
      phytateFlag: "measured",
      phytochemicalTags: [],
      residue: {
        pdpDetectRate: 0.06,
        heavyMetalRisk: 0.38,
        mercuryRisk: 0.04,
        iodineExcessRisk: 0,
        note: "Liver concentrates vitamin A and some contaminants. Residue weight is higher in the organ class.",
        sourceId: "efsa-mrl",
      },
      waterActivity: 0.72,
      fermented: false,
      dried: false,
    },
    animalExclusive: {
      ...MUSCLE_ANIMAL,
      preformedRetinol: true,
    },
    sourceIds: ["usda-fdc-sr", "who-b12", "iom-vitamina"],
    notes: [
      "Preformed retinol 9442 µg RAE/100 g — not carotenoid vitamin A.",
      "Glycogen appears as carbohydrate-by-difference; it is active carb, not fibre.",
    ],
  },
  {
    id: "egg-boiled",
    name: "Egg, whole, hard-boiled",
    nameDe: "Ei, hartgekocht",
    kingdom: "animal",
    foodClass: "eggs",
    fdcId: 173424,
    state: "hard-boiled",
    energyKcal: 155,
    proteinG: 12.58,
    fatG: 10.61,
    aminoAcids: {
      his: 0.298,
      ile: 0.686,
      leu: 1.075,
      lys: 0.904,
      met: 0.392,
      cys: 0.292,
      phe: 0.668,
      tyr: 0.513,
      thr: 0.604,
      trp: 0.153,
      val: 0.767,
    },
    fattyAcids: fa({ sfa: 3.267, mufa: 4.077, pufa: 1.414, ala: 0.035, epa: 0.005, dha: 0.038 }),
    carbs: {
      total: 1.12,
      sugars: 1.12,
      fiber: 0,
      starch: 0,
      starchFlag: "measured",
      resistantStarch: 0,
      resistantStarchFlag: "measured",
    },
    micros: {
      ironMg: 1.19,
      ironForm: "heme",
      hemeFraction: 0.3,
      zincMg: 1.05,
      zincBoundToPhytate: false,
      vitaminARaeUg: 149,
      vitaminAForm: "retinol",
      carotenoidFraction: 0.05,
      vitaminCMg: 0,
      b12Ug: 1.11,
      b12Form: "active",
      folateUg: 44,
      cholineMg: 293.8,
      vitaminDUg: 2.2,
      iodineUg: 24,
      iodineFlag: "estimate",
    },
    quality: {
      ilealDigestibility: 0.97,
      digestibilityFlag: "literature",
      digestibilitySourceId: "who-fao-2013",
      publishedDiaas: 1.13,
      publishedPdcaas: 1,
      qualityIndexSourceId: "phillips-2017-diaas",
      phytateMg: 0,
      phytateFlag: "measured",
      phytochemicalTags: [],
      residue: {
        pdpDetectRate: 0.06,
        heavyMetalRisk: 0.08,
        mercuryRisk: 0,
        iodineExcessRisk: 0,
        note: "Eggs are a low-residue complete-protein food in this model.",
        sourceId: "efsa-mrl",
      },
      waterActivity: 0.75,
      fermented: false,
      dried: false,
    },
    animalExclusive: {
      creatine: false,
      taurine: false,
      carnosine: false,
      longChainEpaDha: true,
      activeB12: true,
      hemeIron: true,
      preformedRetinol: true,
    },
    sourceIds: ["usda-fdc-sr", "phillips-2017-diaas", "who-b12"],
    notes: ["Reference complete protein (DIAAS 1.13). Outstanding choline. Trace DHA."],
  },
  {
    id: "milk-whole",
    name: "Milk, whole 3.25%",
    nameDe: "Vollmilch 3,25 %",
    kingdom: "animal",
    foodClass: "dairy",
    fdcId: 746782,
    state: "whole, 3.25% milkfat — SR typical",
    energyKcal: 61,
    proteinG: 3.15,
    fatG: 3.25,
    aminoAcids: {
      his: 0.089,
      ile: 0.163,
      leu: 0.299,
      lys: 0.264,
      met: 0.083,
      cys: 0.017,
      phe: 0.158,
      tyr: 0.159,
      thr: 0.134,
      trp: 0.04,
      val: 0.192,
    },
    fattyAcids: fa({
      sfa: 1.865,
      mufa: 0.812,
      pufa: 0.195,
      ala: 0.075,
      cla: 0.015,
      oddChain: 0.05,
      claFlag: "estimate",
      oddChainFlag: "estimate",
    }),
    carbs: {
      total: 4.8,
      sugars: 5.05,
      fiber: 0,
      starch: 0,
      starchFlag: "measured",
      resistantStarch: 0,
      resistantStarchFlag: "measured",
    },
    micros: {
      ironMg: 0.03,
      ironForm: "heme",
      hemeFraction: 0,
      zincMg: 0.37,
      zincBoundToPhytate: false,
      vitaminARaeUg: 46,
      vitaminAForm: "retinol",
      carotenoidFraction: 0.1,
      vitaminCMg: 0,
      b12Ug: 0.45,
      b12Form: "active",
      folateUg: 5,
      cholineMg: 14.3,
      vitaminDUg: 1.3,
      iodineUg: 38,
      iodineFlag: "estimate",
    },
    quality: {
      ilealDigestibility: 0.95,
      digestibilityFlag: "literature",
      digestibilitySourceId: "who-fao-2013",
      publishedDiaas: 1.18,
      publishedPdcaas: 1,
      qualityIndexSourceId: "phillips-2017-diaas",
      phytateMg: 0,
      phytateFlag: "measured",
      phytochemicalTags: [],
      residue: {
        pdpDetectRate: 0.08,
        heavyMetalRisk: 0.08,
        mercuryRisk: 0,
        iodineExcessRisk: 0,
        note: "Lactose is active carbohydrate. Calcium bioavailability is a dairy advantage not fully expanded as its own axis.",
        sourceId: "efsa-mrl",
      },
      waterActivity: 0.99,
      fermented: false,
      dried: false,
    },
    animalExclusive: {
      creatine: false,
      taurine: false,
      carnosine: false,
      longChainEpaDha: false,
      activeB12: true,
      hemeIron: false,
      preformedRetinol: true,
    },
    sourceIds: ["usda-fdc-sr", "phillips-2017-diaas", "cla-ruminant"],
    notes: [
      "FDC 746782 is a commonly cited whole-milk record; macros match SR 3.25% milk.",
      "Sugars 5.05 g vs carb 4.8 g is the SR rounding inconsistency; active carb uses sugars.",
    ],
  },
  {
    id: "yogurt-greek-lowfat",
    name: "Greek yogurt, plain, low-fat",
    nameDe: "Griechisches Joghurt, mager",
    kingdom: "animal",
    foodClass: "fermented_animal",
    fdcId: 170903,
    state: "plain, low-fat",
    energyKcal: 73,
    proteinG: 9.95,
    fatG: 1.92,
    aminoAcids: {
      his: 0.281,
      ile: 0.515,
      leu: 0.944,
      lys: 0.834,
      met: 0.262,
      cys: 0.054,
      phe: 0.499,
      tyr: 0.502,
      thr: 0.423,
      trp: 0.126,
      val: 0.606,
    },
    fattyAcids: fa({
      sfa: 1.23,
      mufa: 0.486,
      pufa: 0.076,
      ala: 0.007,
      cla: 0.01,
      oddChain: 0.03,
      claFlag: "estimate",
      oddChainFlag: "estimate",
    }),
    carbs: {
      total: 3.94,
      sugars: 3.56,
      fiber: 0,
      starch: 0.38,
      starchFlag: "derived",
      resistantStarch: 0,
      resistantStarchFlag: "measured",
    },
    micros: {
      ironMg: 0.04,
      ironForm: "nonheme",
      hemeFraction: 0,
      zincMg: 0.6,
      zincBoundToPhytate: false,
      vitaminARaeUg: 90,
      vitaminAForm: "retinol",
      carotenoidFraction: 0.05,
      vitaminCMg: 0.8,
      b12Ug: 0.52,
      b12Form: "active",
      folateUg: 12,
      cholineMg: 15.2,
      vitaminDUg: 0,
      iodineUg: 20,
      iodineFlag: "estimate",
    },
    quality: {
      ilealDigestibility: 0.95,
      digestibilityFlag: "literature",
      digestibilitySourceId: "who-fao-2013",
      publishedDiaas: 1.18,
      publishedPdcaas: 1,
      qualityIndexSourceId: "phillips-2017-diaas",
      phytateMg: 0,
      phytateFlag: "measured",
      phytochemicalTags: ["fermented_acids"],
      residue: {
        pdpDetectRate: 0.08,
        heavyMetalRisk: 0.08,
        mercuryRisk: 0,
        iodineExcessRisk: 0,
        note: "Fermented dairy — not sauerkraut, not unfermented milk.",
        sourceId: "efsa-mrl",
      },
      waterActivity: 0.96,
      fermented: true,
      dried: false,
    },
    animalExclusive: {
      creatine: false,
      taurine: false,
      carnosine: false,
      longChainEpaDha: false,
      activeB12: true,
      hemeIron: false,
      preformedRetinol: true,
    },
    sourceIds: ["usda-fdc-sr", "phillips-2017-diaas"],
    notes: [
      "Concentrated dairy proteins (DIAAS of milk proteins). Fermentation does not add plant fibre.",
      "FDC 170903 lists tryptophan 0.03 g/100 g, which is implausible for 9.95 g dairy protein. EAA grams are scaled from whole-milk SR amino acids (derived).",
    ],
  },
];

export function foodById(id: string): Food | undefined {
  return FOODS.find((food) => food.id === id);
}
